### PR TITLE
Fixed overhang on Homepage card grid

### PR DESCRIPTION
**Pull request by JoeButler7**
### What does this PR do?
Fixes the overhang of the grid over the background on the Homepage

Requesting review from @jcfilben

### CODE REVIEW

**Comment by JoeButler7** [comment]
### Update:
Removed stack and instead use negative margin

**Comment by ShimiSun** [comment]
Needs to resolve conflicts.

**Comment by ShimiSun** [comment]
Looks like you are still missing a closing tag.

**Comment by ShimiSun** [comment]
Conflicts on the Home file.

**Comment by JoeButler7** [comment]
Merge conflicts should be resolved now

**Pull request merged**
